// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: server/proto/game.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature     string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_server_proto_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_game_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *LoginRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *LoginRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_server_proto_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_game_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type ConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_server_proto_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_game_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type MoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	TargetX       float32                `protobuf:"fixed32,2,opt,name=target_x,json=targetX,proto3" json:"target_x,omitempty"`
	TargetY       float32                `protobuf:"fixed32,3,opt,name=target_y,json=targetY,proto3" json:"target_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveRequest) Reset() {
	*x = MoveRequest{}
	mi := &file_server_proto_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveRequest) ProtoMessage() {}

func (x *MoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveRequest.ProtoReflect.Descriptor instead.
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_game_proto_rawDescGZIP(), []int{3}
}

func (x *MoveRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *MoveRequest) GetTargetX() float32 {
	if x != nil {
		return x.TargetX
	}
	return 0
}

func (x *MoveRequest) GetTargetY() float32 {
	if x != nil {
		return x.TargetY
	}
	return 0
}

type MoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveResponse) Reset() {
	*x = MoveResponse{}
	mi := &file_server_proto_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveResponse) ProtoMessage() {}

func (x *MoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveResponse.ProtoReflect.Descriptor instead.
func (*MoveResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_game_proto_rawDescGZIP(), []int{4}
}

func (x *MoveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MoveResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type CollectLootRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	LootId        string                 `protobuf:"bytes,2,opt,name=loot_id,json=lootId,proto3" json:"loot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectLootRequest) Reset() {
	*x = CollectLootRequest{}
	mi := &file_server_proto_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectLootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectLootRequest) ProtoMessage() {}

func (x *CollectLootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectLootRequest.ProtoReflect.Descriptor instead.
func (*CollectLootRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_game_proto_rawDescGZIP(), []int{5}
}

func (x *CollectLootRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *CollectLootRequest) GetLootId() string {
	if x != nil {
		return x.LootId
	}
	return ""
}

type CollectLootResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Success             bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage        string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	NewEncryptedBalance string                 `protobuf:"bytes,3,opt,name=new_encrypted_balance,json=newEncryptedBalance,proto3" json:"new_encrypted_balance,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CollectLootResponse) Reset() {
	*x = CollectLootResponse{}
	mi := &file_server_proto_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectLootResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectLootResponse) ProtoMessage() {}

func (x *CollectLootResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectLootResponse.ProtoReflect.Descriptor instead.
func (*CollectLootResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_game_proto_rawDescGZIP(), []int{6}
}

func (x *CollectLootResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CollectLootResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *CollectLootResponse) GetNewEncryptedBalance() string {
	if x != nil {
		return x.NewEncryptedBalance
	}
	return ""
}

// Game State Messages
type GameStateUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	ServerTime    int64                  `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	Players       []*Player              `protobuf:"bytes,3,rep,name=players,proto3" json:"players,omitempty"`
	LootItems     []*LootItem            `protobuf:"bytes,4,rep,name=loot_items,json=lootItems,proto3" json:"loot_items,omitempty"`
	Npcs          []*NPC                 `protobuf:"bytes,5,rep,name=npcs,proto3" json:"npcs,omitempty"`
	Hazards       []*Hazard              `protobuf:"bytes,6,rep,name=hazards,proto3" json:"hazards,omitempty"`
	Events        []*GameEvent           `protobuf:"bytes,7,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameStateUpdate) Reset() {
	*x = GameStateUpdate{}
	mi := &file_server_proto_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameStateUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStateUpdate) ProtoMessage() {}

func (x *GameStateUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStateUpdate.ProtoReflect.Descriptor instead.
func (*GameStateUpdate) Descriptor() ([]byte, []int) {
	return file_server_proto_game_proto_rawDescGZIP(), []int{7}
}

func (x *GameStateUpdate) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GameStateUpdate) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *GameStateUpdate) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *GameStateUpdate) GetLootItems() []*LootItem {
	if x != nil {
		return x.LootItems
	}
	return nil
}

func (x *GameStateUpdate) GetNpcs() []*NPC {
	if x != nil {
		return x.Npcs
	}
	return nil
}

func (x *GameStateUpdate) GetHazards() []*Hazard {
	if x != nil {
		return x.Hazards
	}
	return nil
}

func (x *GameStateUpdate) GetEvents() []*GameEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	X             float32                `protobuf:"fixed32,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,4,opt,name=y,proto3" json:"y,omitempty"`
	Health        int32                  `protobuf:"varint,5,opt,name=health,proto3" json:"health,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"` // alive, extracted, eliminated
	Kills         int32                  `protobuf:"varint,7,opt,name=kills,proto3" json:"kills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_server_proto_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_server_proto_game_proto_rawDescGZIP(), []int{8}
}

func (x *Player) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Player) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Player) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Player) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Player) GetHealth() int32 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *Player) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Player) GetKills() int32 {
	if x != nil {
		return x.Kills
	}
	return 0
}

type LootItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ItemType      string                 `protobuf:"bytes,2,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"`
	X             float32                `protobuf:"fixed32,3,opt,name=x,proto3" json:"x,omitempty"` // Note: In production, these might be hidden or approximate for FOW
	Y             float32                `protobuf:"fixed32,4,opt,name=y,proto3" json:"y,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // available, collected
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LootItem) Reset() {
	*x = LootItem{}
	mi := &file_server_proto_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LootItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LootItem) ProtoMessage() {}

func (x *LootItem) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LootItem.ProtoReflect.Descriptor instead.
func (*LootItem) Descriptor() ([]byte, []int) {
	return file_server_proto_game_proto_rawDescGZIP(), []int{9}
}

func (x *LootItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LootItem) GetItemType() string {
	if x != nil {
		return x.ItemType
	}
	return ""
}

func (x *LootItem) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *LootItem) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *LootItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type NPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NpcType       string                 `protobuf:"bytes,2,opt,name=npc_type,json=npcType,proto3" json:"npc_type,omitempty"`
	X             float32                `protobuf:"fixed32,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,4,opt,name=y,proto3" json:"y,omitempty"`
	Health        int32                  `protobuf:"varint,5,opt,name=health,proto3" json:"health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NPC) Reset() {
	*x = NPC{}
	mi := &file_server_proto_game_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NPC) ProtoMessage() {}

func (x *NPC) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_game_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NPC.ProtoReflect.Descriptor instead.
func (*NPC) Descriptor() ([]byte, []int) {
	return file_server_proto_game_proto_rawDescGZIP(), []int{10}
}

func (x *NPC) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NPC) GetNpcType() string {
	if x != nil {
		return x.NpcType
	}
	return ""
}

func (x *NPC) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *NPC) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *NPC) GetHealth() int32 {
	if x != nil {
		return x.Health
	}
	return 0
}

type Hazard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	HazardType    string                 `protobuf:"bytes,2,opt,name=hazard_type,json=hazardType,proto3" json:"hazard_type,omitempty"`
	X             float32                `protobuf:"fixed32,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,4,opt,name=y,proto3" json:"y,omitempty"`
	Radius        float32                `protobuf:"fixed32,5,opt,name=radius,proto3" json:"radius,omitempty"`
	IsActive      bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hazard) Reset() {
	*x = Hazard{}
	mi := &file_server_proto_game_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hazard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hazard) ProtoMessage() {}

func (x *Hazard) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_game_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hazard.ProtoReflect.Descriptor instead.
func (*Hazard) Descriptor() ([]byte, []int) {
	return file_server_proto_game_proto_rawDescGZIP(), []int{11}
}

func (x *Hazard) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Hazard) GetHazardType() string {
	if x != nil {
		return x.HazardType
	}
	return ""
}

func (x *Hazard) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Hazard) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Hazard) GetRadius() float32 {
	if x != nil {
		return x.Radius
	}
	return 0
}

func (x *Hazard) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type GameEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	TargetId      string                 `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Data          string                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"` // JSON string for flexible event data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameEvent) Reset() {
	*x = GameEvent{}
	mi := &file_server_proto_game_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEvent) ProtoMessage() {}

func (x *GameEvent) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_game_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEvent.ProtoReflect.Descriptor instead.
func (*GameEvent) Descriptor() ([]byte, []int) {
	return file_server_proto_game_proto_rawDescGZIP(), []int{12}
}

func (x *GameEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *GameEvent) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *GameEvent) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *GameEvent) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_server_proto_game_proto protoreflect.FileDescriptor

const file_server_proto_game_proto_rawDesc = "" +
	"\n" +
	"\x17server/proto/game.proto\x12\x04game\"e\n" +
	"\fLoginRequest\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"O\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\")\n" +
	"\x0eConnectRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\"\\\n" +
	"\vMoveRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x19\n" +
	"\btarget_x\x18\x02 \x01(\x02R\atargetX\x12\x19\n" +
	"\btarget_y\x18\x03 \x01(\x02R\atargetY\"M\n" +
	"\fMoveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"F\n" +
	"\x12CollectLootRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x17\n" +
	"\aloot_id\x18\x02 \x01(\tR\x06lootId\"\x88\x01\n" +
	"\x13CollectLootResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x122\n" +
	"\x15new_encrypted_balance\x18\x03 \x01(\tR\x13newEncryptedBalance\"\x92\x02\n" +
	"\x0fGameStateUpdate\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\x03R\n" +
	"serverTime\x12&\n" +
	"\aplayers\x18\x03 \x03(\v2\f.game.PlayerR\aplayers\x12-\n" +
	"\n" +
	"loot_items\x18\x04 \x03(\v2\x0e.game.LootItemR\tlootItems\x12\x1d\n" +
	"\x04npcs\x18\x05 \x03(\v2\t.game.NPCR\x04npcs\x12&\n" +
	"\ahazards\x18\x06 \x03(\v2\f.game.HazardR\ahazards\x12'\n" +
	"\x06events\x18\a \x03(\v2\x0f.game.GameEventR\x06events\"\x96\x01\n" +
	"\x06Player\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\f\n" +
	"\x01x\x18\x03 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x02R\x01y\x12\x16\n" +
	"\x06health\x18\x05 \x01(\x05R\x06health\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x14\n" +
	"\x05kills\x18\a \x01(\x05R\x05kills\"k\n" +
	"\bLootItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\titem_type\x18\x02 \x01(\tR\bitemType\x12\f\n" +
	"\x01x\x18\x03 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x02R\x01y\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"d\n" +
	"\x03NPC\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bnpc_type\x18\x02 \x01(\tR\anpcType\x12\f\n" +
	"\x01x\x18\x03 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x02R\x01y\x12\x16\n" +
	"\x06health\x18\x05 \x01(\x05R\x06health\"\x8a\x01\n" +
	"\x06Hazard\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vhazard_type\x18\x02 \x01(\tR\n" +
	"hazardType\x12\f\n" +
	"\x01x\x18\x03 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x02R\x01y\x12\x16\n" +
	"\x06radius\x18\x05 \x01(\x02R\x06radius\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\"x\n" +
	"\tGameEvent\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\tR\btargetId\x12\x12\n" +
	"\x04data\x18\x04 \x01(\tR\x04data2?\n" +
	"\vAuthService\x120\n" +
	"\x05Login\x12\x12.game.LoginRequest\x1a\x13.game.LoginResponse2\xba\x01\n" +
	"\vGameService\x128\n" +
	"\aConnect\x12\x14.game.ConnectRequest\x1a\x15.game.GameStateUpdate0\x01\x12-\n" +
	"\x04Move\x12\x11.game.MoveRequest\x1a\x12.game.MoveResponse\x12B\n" +
	"\vCollectLoot\x12\x18.game.CollectLootRequest\x1a\x19.game.CollectLootResponseB*Z(github.com/koded/fog-of-war/server/protob\x06proto3"

var (
	file_server_proto_game_proto_rawDescOnce sync.Once
	file_server_proto_game_proto_rawDescData []byte
)

func file_server_proto_game_proto_rawDescGZIP() []byte {
	file_server_proto_game_proto_rawDescOnce.Do(func() {
		file_server_proto_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_proto_game_proto_rawDesc), len(file_server_proto_game_proto_rawDesc)))
	})
	return file_server_proto_game_proto_rawDescData
}

var file_server_proto_game_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_server_proto_game_proto_goTypes = []any{
	(*LoginRequest)(nil),        // 0: game.LoginRequest
	(*LoginResponse)(nil),       // 1: game.LoginResponse
	(*ConnectRequest)(nil),      // 2: game.ConnectRequest
	(*MoveRequest)(nil),         // 3: game.MoveRequest
	(*MoveResponse)(nil),        // 4: game.MoveResponse
	(*CollectLootRequest)(nil),  // 5: game.CollectLootRequest
	(*CollectLootResponse)(nil), // 6: game.CollectLootResponse
	(*GameStateUpdate)(nil),     // 7: game.GameStateUpdate
	(*Player)(nil),              // 8: game.Player
	(*LootItem)(nil),            // 9: game.LootItem
	(*NPC)(nil),                 // 10: game.NPC
	(*Hazard)(nil),              // 11: game.Hazard
	(*GameEvent)(nil),           // 12: game.GameEvent
}
var file_server_proto_game_proto_depIdxs = []int32{
	8,  // 0: game.GameStateUpdate.players:type_name -> game.Player
	9,  // 1: game.GameStateUpdate.loot_items:type_name -> game.LootItem
	10, // 2: game.GameStateUpdate.npcs:type_name -> game.NPC
	11, // 3: game.GameStateUpdate.hazards:type_name -> game.Hazard
	12, // 4: game.GameStateUpdate.events:type_name -> game.GameEvent
	0,  // 5: game.AuthService.Login:input_type -> game.LoginRequest
	2,  // 6: game.GameService.Connect:input_type -> game.ConnectRequest
	3,  // 7: game.GameService.Move:input_type -> game.MoveRequest
	5,  // 8: game.GameService.CollectLoot:input_type -> game.CollectLootRequest
	1,  // 9: game.AuthService.Login:output_type -> game.LoginResponse
	7,  // 10: game.GameService.Connect:output_type -> game.GameStateUpdate
	4,  // 11: game.GameService.Move:output_type -> game.MoveResponse
	6,  // 12: game.GameService.CollectLoot:output_type -> game.CollectLootResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_server_proto_game_proto_init() }
func file_server_proto_game_proto_init() {
	if File_server_proto_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_proto_game_proto_rawDesc), len(file_server_proto_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_server_proto_game_proto_goTypes,
		DependencyIndexes: file_server_proto_game_proto_depIdxs,
		MessageInfos:      file_server_proto_game_proto_msgTypes,
	}.Build()
	File_server_proto_game_proto = out.File
	file_server_proto_game_proto_goTypes = nil
	file_server_proto_game_proto_depIdxs = nil
}
